
include ../mk.global

PROGRAM = 
LIBRARY = libdprstrings.a

CSOURCES    = 
CLIBSOURCES = dprstrings.c

LDDIRS_extra = -L.
LDLIBS_extra = -ldprstrings

INSTALL_LOCAL = install_local

include ../mk.targets

dprstrings.o: dprstrings.h


